[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_GA_ID = "G-VSDK6W40MJ"
  NEXT_PUBLIC_META_PIXEL_ID = "4412355655744461"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://www.canwellinteriors.com/*"
  to = "https://canwellinteriors.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
